### ISSUE TITLE
Mobile sync hook triggers a duplicate, same-day review

### ISSUE THREAD

**Issue by bmulholland** [hgiesel/anki_straight_reward#1]
I am being shown a card for review a second time in the same day, even though the review was successful the first time. It happens for some (but not all) cards that are reviewed on mobile that then trigger a SR straight during a sync to my computer. I have verified this all by checking the review history log for two cards and cross-referencing with the SR sync log.

As an example of the "some, not all": I can review the card a second time on mobile and not trigger the same issue. However, when I review the card a second time (via mobile or computer), it triggers a second ease increase.

For example, card ID 1537014055629 (stats via https://ankiweb.net/shared/info/1008566916). Notice that I reviewed today, that it's in Review, that the interval is 25d, that it was adjusted by Straight Reward (see log below), and yet it's due (again) today.

<img width="367" alt="Screen Shot 2020-03-09 at 21 10 23" src="https://user-images.githubusercontent.com/247713/76253147-66cc7a00-624a-11ea-8ba2-d0ffb8b885e6.png">

This only started after I installed Straight Reward. While I have other add-ons installed, none of them affect the cards themselves (stuff like AwesomeTTS, Review Heatmap, etc). I'm on the latest Straight Reward (via Check for Updates) and Anki (2.1.21). My phone is on the latest Anki for iOS. I sync obsessively, and the devices were certainly in sync before I started the mobile reviews.

The cards in question are in a nested deck; I haven't done further testing so that may or may not be relevant.

Sync log:
```
### Ease Changes applied in collection 1575342000 on 2020-03-09 20:15:49.084518:
1537014055428: Light Study: 25
1537014055943: Light Study: 30
1537014056457: Light Study: 15
1497484863508: Default: 15
1537014056486: Light Study: 20
1497484864053: Default: 15
1497484863543: Default: 15
1537014055992: Light Study: 15
1497484862535: Default: 15
1537014055502: Light Study: 30
1497484862033: Default: 15
1537014057557: Light Study: 15
1497484864120: Default: 15
1497484862076: Default: 15
1537014056065: Light Study: 15
1576075993232: Default: 30
1537014060697: Light Study: 15
1537014055589: Light Study: 30
1576017133737: Default: 30
1537014055607: Light Study: 30
1576016875706: Default: 30
1537014055629: Light Study: 20
1497484862674: Default: 20
1575494700244: Default: 25
1537014055671: Light Study: 15
1497484862206: Default: 15
1537014056197: Light Study: 20
1575494015237: Default: 25
1497484863770: Default: 20
1537014056222: Light Study: 15
1497484862750: Default: 15
1575494015276: Default: 30
1537014055221: Light Study: 30
1497484864347: Default: 15
1537014056299: Light Study: 15
1497484863863: Default: 15
1537014056317: Light Study: 15
1537014055296: Light Study: 30
1537014055813: Light Study: 15
1537014055814: Light Study: 25
1537014056344: Light Study: 20
1537014055322: Light Study: 20
1576610189727: Default: 35
1497484862405: Default: 30
1497484862939: Default: 15
1537014055906: Light Study: 30
1537014055405: Light Study: 30
1537014056437: Light Study: 20
1537014055417: Light Study: 15
```

**Comment by hgiesel** [comment]
Thanks for the report! I will have a look into this.

**Comment by hgiesel** [comment]
I tried to recreate this bug, but couldn't. A few questions:

1. How come the interval jumped from 1.7mo to 25d even though you rated Good?
2. Did you use filtered decks?
3. If something funny was going on during the sync, it would probably crash the sync (which isn't terrible, but it would stop you from syncing again for some time, and you would certainly notice). That's why I don't think something is wrong with the sync.

**Comment by hgiesel** [comment]
On the newest version (v0.2.1) I added debugging for problems while syncing. If really something unexpected happened during syncing, this would log it to the sync_log.

**Comment by bmulholland** [comment]
Hey! Thanks for the addon, and for investigating. Is it possible that something the sync is doing has unintended side effects? Thus not causing a crash.

Regarding your questions:
1. I have no idea why the interval looks funny; I didn't do anything to the card and I don't have any other addons that could affect the interval.
2. I do not use any filtering or filtered decks.

I'll upgrade to the latest and try to repro.

**Comment by bmulholland** [comment]
I managed to reproduce a few times today; none of them triggered the exception logging that you added. I had a hunch that it's a race condition and have found some evidence for that, below. **A potential fix is to add `card.load()` as the first line of `force_ease_change`; I've made that change locally and will see if it helps tomorrow.**

Here's a card (1574587965715) that was affected:
<img width="511" alt="Screen Shot 2020-03-12 at 13 29 31" src="https://user-images.githubusercontent.com/247713/76521643-8390c980-6465-11ea-962b-fc18218d06f2.png">

Here's sync_log, including some logging that I'd added around `flushSched` based on my hunch (exerted here, full log at bottom). The due date in the output I added is `card.due` before and after `flushSched` - I suspected there would be a change; there obviously wasn't.
```
BM: Applying ease change for 1574587965715, adding 150. Due date starts at 100 and after flush due date is 100
### Ease Changes applied in collection 1575342000 on 2020-03-12 13:15:33.882859:
1574587965715: Light Study: 15
```

I found two back-to-back calls for this same card in Anki's `collection.log` (see below). The first, newerRows, is from Anki's native sync, which sets due to 111 and interval to 11 ([you can cross-check the order here](https://github.com/ankitects/anki/blob/862e2b48f06dadf414d171d2cfdc4ac3ad79e7da/pylib/anki/cards.py#L127)). **The second set is the client chunk that _I assume_ is from SR, which sets due to 100 and interval to 5**

Given all that, perhaps SR's card update is based on card data that hasn't been updated for the new review. I don't have enough understanding to figure out the architectural reasons for a timing issue, but something simple that should reduce (maybe eliminate?) the frequency of occurrence is to refresh the card data just before updating it. It looks like `card.load()` ([ref](https://github.com/ankitects/anki/blob/862e2b48f06dadf414d171d2cfdc4ac3ad79e7da/pylib/anki/cards.py#L63)) will do the trick, so I've locally added that to `force_ease_change` so that the code now reloads the card before changing the factor, and  updating the DB via `flushSched`. **However, buyer beware: I am changing code I don't fully understand, so I can't guarantee there aren't side effects.**

Excerpted collection.log (I've cut out other cards for clarity):
```
[1584015333] sync.py:newerRows(): cards, [
 [1574587965715,
  1574587965617,
  1579542134235,
  3,
  1584015226,
  2231,
  2,
  2,
  111,
  11,
  2300,
  19,
  1,
  1001,
  0,
  0,
  0,
  ''],
  ]
[1584015333] sync.py:newerRows(): notes, []
[1584015333] sync.py:sync(): client chunk, {'cards': [
           (1574587965715,
            1574587965617,
            1579542134235,
            3,
            1584015333,
            2231,
            2,
            2,
            100,
            5,
            2450,
            18,
            1,
            1001,
            0,
            0,
            0,
            '')],
 'done': True,
 'notes': [],
 'revlog': []}
[1584015334] sync.py:sync(): findChanges
```

Full sync_log for the relevant sync:
```
BM: Applying ease change for 1574587964973, adding 200. Due date starts at 116 and after flush due date is 116
BM: Applying ease change for 1574587965532, adding 0. Due date starts at 126 and after flush due date is 126
BM: Applying ease change for 1574587964921, adding 200. Due date starts at 111 and after flush due date is 111
BM: Applying ease change for 1574587965175, adding 150. Due date starts at 106 and after flush due date is 106
BM: Applying ease change for 1574587965715, adding 150. Due date starts at 100 and after flush due date is 100
BM: Applying ease change for 1574587965215, adding 150. Due date starts at 106 and after flush due date is 106
BM: Applying ease change for 1574587965294, adding 0. Due date starts at 173 and after flush due date is 173
BM: Applying ease change for 1574587964837, adding 0. Due date starts at 124 and after flush due date is 124
BM: Applying ease change for 1574587964843, adding 0. Due date starts at 124 and after flush due date is 124
BM: Applying ease change for 1521483292141, adding 0. Due date starts at 123 and after flush due date is 123
BM: Applying ease change for 1521483292153, adding 0. Due date starts at 126 and after flush due date is 126
### Ease Changes applied in collection 1575342000 on 2020-03-12 13:15:33.882859:
1574587964973: Light Study: 20
1574587964921: Light Study: 20
1574587965175: Light Study: 15
1574587965715: Light Study: 15
1574587965215: Light Study: 15
```

(For my own reference, here's a filter to get a list of affected cards:
rated:1 is:due is:review
)

**Comment by destel** [comment]
I have exact same issue for multiple cards. In addition to that few of that cards got their ease increased even though it already was 250%
<img width="643" alt="Screenshot 2020-03-13 at 10 24 08" src="https://user-images.githubusercontent.com/2601311/76603071-f73ddf80-6514-11ea-9ad8-170f38c3b6af.png">

**Comment by bmulholland** [comment]
@destel Could you file a second issue for the >250% bug?

**Comment by bmulholland** [comment]
My fix didn't work; I just had a sync where this happened on 10% of cards.

It looks like the SR hooks are monkey-patched into the middle of sync processing, which would be why there's a race condition here. It would be better to do all the SR processing at the end of sync, when all the updates from mobile have finished executing. A hook on `sync_stage_did_change` would probably do it...

@hgiesel It looks like you had good reason to do this sync approach, especially with the temp comparelog table you're doing. Could you explain the approach a bit? Why couldn't you use the same functions as the review hooks?

**Comment by destel** [comment]
@bmulholland I've just created an issue https://github.com/hgiesel/anki_straight_reward/issues/4

**Comment by bmulholland** [comment]
@hgiesel I forgot to ask: Would you prefer to figure it out yourself? Is what I've done so far helpful? Is there any other ways in which I could help?

**Comment by hgiesel** [comment]
@bmulholland 
The approach for the sync_hook is the following:

All reviews are logged in the anki sqlite database table `revlog`.
So I save all previous entries as `comparelog` and the difference between the `revlog` after syncing and the comparelog is the set of new reviews.

I have to do this during the sync, because otherwise I cannot reconstruct which reviews are new, and which are old (have already been considered). Reviews have the time of review logged, and my first thought was to get new reviews by comparing with the time of the last sync: however that doesn't check out, because you can also do reviews locally, without syncing. That would mean that some reviews are considered twice.

If you have time to figure it out, I'd really appreciate it. I'm a bit busy for the coming week, but otherwise I'll get to it the in the coming weeks at the latest.

**Comment by bmulholland** [comment]
@hgiesel That all makes sense, thanks for explaining. It does seem tricky without a way to get the list of new reviews from the normal sync hooks.

What do you think about an approach that only collects all the reviews during the sync and then processes  those reviews & straights after the sync is complete? That way SR isn't modifying data at the same time as Anki's sync,  so there shouldn't be any race condition.

**Comment by hgiesel** [comment]
Yes I also figured this should be the approach to go for. That could also be registered on a normal gui hook.

**Comment by hgiesel** [comment]
@bmulholland 
I just saw that you forked the project. To avoid doubling the effort, I'll let you know what I figured out:

I just had a look on the `anki.hooks` hooks `sync_progress_did_change`, and `sync_stage_did_change`:

```
### Problem while syncing ease changes in collection my stage on 2020-03-15 18:30:15.920217:
login
### Problem while syncing ease changes in collection my stage on 2020-03-15 18:30:16.054393:
meta
### Problem while syncing ease changes in collection my stage on 2020-03-15 18:30:16.179823:
server
### Problem while syncing ease changes in collection my stage on 2020-03-15 18:30:16.188606:
stream
### Ease Changes applied in collection 1583258400 on 2020-03-15 18:30:16.234665:

### Problem while syncing ease changes in collection my stage on 2020-03-15 18:30:16.235164:
client
### Problem while syncing ease changes in collection my stage on 2020-03-15 18:30:16.235565:
stream
### Problem while syncing ease changes in collection my stage on 2020-03-15 18:30:16.270347:
sanity
### Problem while syncing ease changes in collection my stage on 2020-03-15 18:30:16.314414:
finalize
### Problem while syncing ease changes in collection my stage on 2020-03-15 18:30:16.383238:
findMedia
```

I don't see when `sync_progress_did_change` is called, but the other one might suit our purposes. I'd try creating the comparelog at `stream` or `server`, and updating ease at `finalize`, and see whether it works for you when.

I'd be happy to accept you pull request :)

**Comment by bmulholland** [comment]
@hgiesel I was thinking of doing something similar, but how would I get the data to create the comparelog at `stream` or `server`? Definitely `finalize` for the final update, though.

`sync_stage_did_change` is called e.g. https://github.com/ankitects/anki/blob/244326c130111619877c44cdc56115fc6e6362c6/pylib/anki/sync.py#L142

**Comment by bmulholland** [comment]
There's another wrinkle: I can't figure out a way to get the collection in a new-style hook during sync. See my question here: https://anki.tenderapp.com/discussions/add-ons/42645-getting-collection-during-new-style-sync-hook?unresolve=true

Do you have any ideas?

In the meantime, I've got a fix that still monkey-patches, but later on. I'll test it now, and create a PR so you can see what I've got so far.
