### ISSUE TITLE
Keep settings when exporting/importing

### ISSUE THREAD

**Issue by galantra** [hgiesel/anki_straight_reward#10]
As of now, the settings have been changed to default after importing/exporting a deck. I don't know if the problem is the export or the import step.

**Comment by hgiesel** [comment]
Certainly an interesting idea. At the moment I don't see a way to do implement it though. Would need to do some research about how apkg files are generated.

**Comment by hgiesel** [comment]
This should work with the master version now. I'm keeping it on hold for a few more days to do some testing.

**Comment by hgiesel** [comment]
v0.4.0 released.
