### ISSUE TITLE
Getting error like this

### ISSUE THREAD

**Issue by kinkeymonkey161** [hgiesel/anki_straight_reward#16]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-07-07 07:50:55

Traceback (most recent call last):
  File "aqt\main.py", line 496, in loadCollection
  File "aqt\gui_hooks.py", line 718, in __call__
  File "C:\Users\Gun\AppData\Roaming\Anki2\addons21\957961234\src\lib\sync_hook.py", line 102, in after_sync
    result = check_cids(col, reviewed_cids)
  File "C:\Users\Gun\AppData\Roaming\Anki2\addons21\957961234\src\lib\sync_hook.py", line 66, in check_cids
    card = Card(col, revcid)
  File "lib\site-packages\anki\cards.py", line 44, in __init__
  File "lib\site-packages\anki\cards.py", line 51, in load
AssertionError

**Comment by hgiesel** [comment]
Hm, these seems to imply that you reviewed cards which do not exist in the collection you try to sync with.

Do you happen to create cards on mobile? Either AnkiMobile on iOS or AnkiDroid?

**Comment by kinkeymonkey161** [comment]
I don't create cards on mobile.I did it in my other profile in Windows Anki and also I have never synced that profile with Anki.

**Comment by hgiesel** [comment]
So you have multiple instances of desktop Anki?
[I had some concerns over this before](https://github.com/hgiesel/anki_straight_reward/issues/15). My recommendation would be to only Straight Reward installed on one of these Anki instances. 

However this here is a different issue altogether, I'll see that I can find some time today to fix it. Thanks for the bug report!

**Comment by kinkeymonkey161** [comment]
Yea, I have multiple profiles in Anki for different experiments and I have got the same error now too.

And how can I install a add on specific to one profile.If I install in one,it gets installed in all the profiles :(

**Comment by hgiesel** [comment]
There's currently no way to do this. I will see that I implement this in the next version.

**Comment by hgiesel** [comment]
You can now update to the newest version, if you restart Anki.
This one should fix your issue: The exception you saw is now captured, also there's a new way to disable the sync hook on a specific profile here: ![settings_image](https://raw.githubusercontent.com/hgiesel/anki_straight_reward/master/images/preferences.png)

**Comment by kinkeymonkey161** [comment]
Thanks a lot for working on it

**Comment by hgiesel** [comment]
I updated it again.

**Comment by kinkeymonkey161** [comment]
Thanks man !
It's fine now
