### ISSUE TITLE
Multiple reviews since last sync?

### ISSUE THREAD

**Issue by buster-blue** [hgiesel/anki_straight_reward#17]
(I would've put this in discussions, but they're not enabled. Sorry about that.)

When a card is reviewed multiple times since the last time you synced to straight rewards, does the card get the straight rewards for every review, or for just one of them. I think only considering one review since last sync makes more sense (since later reviews aren't adjusted for earlier straight rewards, because they didn't get them) but I just wanted to ask, since the addon's behavior in this situation doesn't seem to be documented.

**Comment by hgiesel** [comment]
[I implemented support for this](https://github.com/hgiesel/anki_straight_reward/blob/5431940541fbcb856882a8964f6751420496cf69/src/lib/sync_hook.py#L71). However it's not well tested.

**Comment by buster-blue** [comment]
You're right. It looks like this feature was added in November. I'm not good at reading Python, but the comments suggest that when there are multiple reviews since last sync, only the first of those reviews is considered for a straight reward until the next sync. That's pretty much what I was hoping for. Thanks! I'll keep in mind that it might be buggy.

**Comment by hgiesel** [comment]
And if you notice a bug with this, don't hesitate to report. I've always been meaning to test this, but I would have to stretch the test over 4+ days, which I didn't have the patience to do yet :)
