### ISSUE TITLE
What default value?

### ISSUE THREAD

**Issue by cjdduarte** [hgiesel/anki_straight_reward#24]
In Anki 2.1.50, in the parameters screen, after installing the addon, it is configured with the value "1", but Anki shows that the DEFAULT is "2" and in the tutorial it says that it is "0".

What default value?

![image](https://user-images.githubusercontent.com/42243532/163352622-dcd9ed6f-27f7-4c10-9e52-a421fe794a2f.png)

**Comment by hgiesel** [comment]
Default value is 2 currently
